### ISSUE TITLE
Cannot pull container

### ISSUE THREAD

**Issue by dweemx** [dynverse/babelwhale#4]
Hi,

I tried to pull a singularity container using this function:
```
babelwhale::pull_container(container_id="dynverse/scorpius")
```
But, It throws me an error:
```
ERROR: Unknown command 'pull'
```

It seems that it is related to the `env = c(SINGULARITY_CACHEDIR = tempcache)` argument because
when I run:
```
processx::run(command = "singularity", args = c("pull", "--name", image_file, paste0("shub://",container_id)), echo = TRUE)
```
it does pull the container. Unfortunately, it does pull it in my working directory but doesn't save it automatically in my SINGULARITY_CACHEDIR environment variable.

Any idea why setting this env is causing this error?

This is my environment:
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C 
```

**Comment by rcannood** [comment]
That's strange! @zouter and I will both have limited connectivity for a week, but I will have a look at this asap.

**Comment by rcannood** [comment]
What happens if you run the code in this file manually https://github.com/dynverse/babelwhale/blob/master/R/pull_image.R? Where does it get stuck?

**Comment by dweemx** [comment]
It gets stuck here:
```
# pull container
processx::run(
  command = "singularity",
  args = c("pull", "--name", image_file, paste0("shub://", container_id)),
  env = c("SINGULARITY_CACHEDIR" = tempcache),
  echo = TRUE
)
```

**Comment by rcannood** [comment]
Ha. Sorry for the long wait. It helps a lot to be at a computer to find out what is going wrong :)

All of the docker and singularity containers have a "ti_" prefix. E.g. dynverse/ti_scorpius, dynverse/ti_monocle_ddrtree. The following command should work immediately:
```R
babelwhale::pull_container(container_id="dynverse/ti_scorpius")
```

Could you confirm whether that works?

For the singularity containers, I'm aware the singularity slingshot container is not working (whereas the exact same docker container works fine) ─ I'm trying to figure out what the problem is.

Are you trying to manually run the containers? 

Robrecht

**Comment by zouter** [comment]
With the changes coming up with dynwrap v2, this is issue can be closed
